### ISSUE TITLE
Forms list screen crashing in few samsung, oppo devices 

### ISSUE THREAD

**Issue by konishon** [fieldsight/fieldsight-mobile#472]
Stacktrace from firebase 
https://console.firebase.google.com/project/fieldsight-2906f/crashlytics/app/android:org.bcss.collect.android/issues/b9a7e48888cc8e9e4b8434b61f4f1a42?time=last-twenty-four-hours&sessionId=5DC273F903D200013FE1DEB9E63B20A6_DNE_0_v2

```
Caused by androidx.fragment.app.Fragment$InstantiationException: Unable to instantiate fragment org.fieldsight.naxa.forms.ui.FieldSightFormListFragment: could not find Fragment constructor
       at androidx.fragment.app.Fragment.instantiate(Fragment.java:519)
       at androidx.fragment.app.FragmentContainer.instantiate(FragmentContainer.java:57)
       at androidx.fragment.app.FragmentManagerImpl$5.instantiate(FragmentManagerImpl.java:2788)
       at androidx.fragment.app.FragmentState.instantiate(FragmentState.java:78)
       at androidx.fragment.app.FragmentManagerImpl.restoreSaveState(FragmentManagerImpl.java:2471)
       at androidx.fragment.app.FragmentController.restoreSaveState(FragmentController.java:195)
       at androidx.fragment.app.FragmentActivity.onCreate(FragmentActivity.java:292)
       at androidx.appcompat.app.AppCompatActivity.onCreate(AppCompatActivity.java:106)
       at org.odk.collect.android.activities.CollectAbstractActivity.onCreate(CollectAbstractActivity.java:53)
       at org.fieldsight.naxa.site.FragmentHostActivity.onCreate(FragmentHostActivity.java:66)
       at android.app.Activity.performCreate(Activity.java:7326)
       at android.app.Activity.performCreate(Activity.java:7317)
       at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1271)
       at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3072)
       at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3235)
       at android.app.ActivityThread.handleRelaunchActivityInner(ActivityThread.java:5013)
       at android.app.ActivityThread.handleRelaunchActivity(ActivityThread.java:4922)
       at android.app.servertransaction.ActivityRelaunchItem.execute(ActivityRelaunchItem.java:69)
       at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:108)
       at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:68)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1926)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:214)
       at android.app.ActivityThread.main(ActivityThread.java:6986)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1445)
```

**Comment by konishon** [comment]
This works fine on my device
https://stackoverflow.com/questions/10450348/do-fragments-really-need-an-empty-constructorQD
https://stackoverflow.com/questions/21431545/fragments-are-required-to-have-a-parameterless-constructor-what-if-my-fragment

However, the issue seems to be with the const in the Frament being private
