### ISSUE TITLE
Syns crashes when trying to download multiple projects

### ISSUE THREAD

**Issue by konishon** [fieldsight/fieldsight-mobile#509]
#### Software and hardware versions 
FieldSight v.3.3.4, Android 10

#### Problem description
Download fails when downloading multiple projects

#### Steps to reproduce the problem
1. Open sync 
2. Select multiple projects
3. Tap download

#### Expected behavior
1. Open sync 
2. Select multiple projects
3. Tap download
4. Download should suceeed

#### Other information 
```
 java.lang.NullPointerException: The iterator returned a null value
        at io.reactivex.internal.functions.ObjectHelper.requireNonNull(ObjectHelper.java:39)
        at io.reactivex.internal.operators.observable.ObservableFlattenIterable$FlattenIterableObserver.onNext(ObservableFlattenIterable.java:103)
        at io.reactivex.internal.operators.observable.ObservableScalarXMap$ScalarDisposable.run(ObservableScalarXMap.java:248)
        at io.reactivex.internal.operators.observable.ObservableJust.subscribeActual(ObservableJust.java:35)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableFlattenIterable.subscribeActual(ObservableFlattenIterable.java:44)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableFilter.subscribeActual(ObservableFilter.java:30)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableMap.subscribeActual(ObservableMap.java:32)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableFlattenIterable.subscribeActual(ObservableFlattenIterable.java:44)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.internal.operators.observable.ObservableConcatMap.subscribeActual(ObservableConcatMap.java:53)
        at io.reactivex.Observable.subscribe(Observable.java:12267)
        at io.reactivex.Observable.subscribe(Observable.java:12253)
        at io.reactivex.Observable.subscribe(Observable.java:12181)
        at org.fieldsight.naxa.v3.network.SyncServiceV3.onHandleIntent(SyncServiceV3.java:256)
        at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:135)
        at android.os.HandlerThread.run(HandlerThread.java:61)
```

**Comment by konishon** [comment]
Closed by https://github.com/fieldsight/fieldsight-mobile/pull/505/commits/728f335a8fa14e133b617c474ba71d848838b0b9
